

[project]
name = "test"
binary_dir = "example/build/"

[target.main]
# name = "main"
build_dir = "main/" # might be required
src_files = ["example/main.cpp", "example/helper.cpp"] # required
type = "root" # required
deps = ["printlib"] # not required
include_dirs = ["example/"] # not required


[target.printlib]
build_dir = "printlib/"
src_files = ["example/printlib/lib.cpp"]
include_dirs = ["example/printlib/"]
type = "dep"
