

[project]
name = "test"
binary_dir = "example/build/"

[target]
name = "main"
build_dir = "main/"
src_files = ["example/test.cpp"]
type = {bin_type = "exec", run_type = "main"}
deps = {}
# deps = ["testC"]

